In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("cibil_nn.csv")

In [3]:
df.head()

,Unnamed: 0,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,...,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,max_unsec_exposure_inPct,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,45,46,12,7,5,7,4,0.583,0.333,0.417,...,1.0,0.615,1.000,7.729,0,0,CC,others,651,P4
1,183,184,9,5,4,0,0,0.000,0.000,0.444,...,1.0,0.286,0.286,23.113,0,0,PL,others,672,P2
2,351,352,4,0,4,1,0,0.250,0.000,1.000,...,0.0,0.000,0.000,5.582,0,1,HL,CC,689,P2
3,403,404,129,122,7,0,7,0.000,0.054,0.054,...,1.0,0.500,0.429,2.218,1,0,ConsumerLoan,AL,649,P4
4,493,494,4,1,3,1,0,0.250,0.000,0.750,...,1.0,0.333,1.000,6.192,0,0,PL,PL,662,P3


In [4]:
df.columns

Index(['Unnamed: 0', 'PROSPECTID', 'Total_TL', 'Tot_Closed_TL',
       'Tot_Active_TL', 'Total_TL_opened_L6M', 'Tot_TL_closed_L6M',
       'pct_tl_open_L6M', 'pct_tl_closed_L6M', 'pct_active_tl',
       'pct_closed_tl', 'Total_TL_opened_L12M', 'Tot_TL_closed_L12M',
       'pct_tl_open_L12M', 'pct_tl_closed_L12M', 'Tot_Missed_Pmnt', 'Auto_TL',
       'CC_TL', 'Consumer_TL', 'Gold_TL', 'Home_TL', 'PL_TL', 'Secured_TL',
       'Unsecured_TL', 'Other_TL', 'Age_Oldest_TL', 'Age_Newest_TL',
       'time_since_recent_payment', 'time_since_first_deliquency',
       'time_since_recent_deliquency', 'num_times_delinquent',
       'max_delinquency_level', 'max_recent_level_of_deliq', 'num_deliq_6mts',
       'num_deliq_12mts', 'num_deliq_6_12mts', 'max_deliq_6mts',
       'max_deliq_12mts', 'num_times_30p_dpd', 'num_times_60p_dpd', 'num_std',
       'num_std_6mts', 'num_std_12mts', 'num_sub', 'num_sub_6mts',
       'num_sub_12mts', 'num_dbt', 'num_dbt_6mts', 'num_dbt_12mts', 'num_lss',
       'num

In [5]:
df.shape

(585, 88)

In [6]:
df.describe()

,Unnamed: 0,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,...,PL_utilization,PL_Flag,pct_PL_enq_L6m_of_L12m,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,max_unsec_exposure_inPct,HL_Flag,GL_Flag,Credit_Score
count,585.000000,585.000000,585.000000,585.000000,585.000000,585.000000,585.000000,585.000000,585.000000,585.000000,...,585.000000,585.0,585.000000,585.000000,585.000000,585.000000,585.000000,585.000000,585.000000,585.000000
mean,25600.707692,25601.707692,14.517949,8.170940,6.347009,1.849573,1.328205,0.146655,0.083145,0.553010,...,0.724156,1.0,0.422656,0.326350,0.250899,0.193287,242.707275,0.379487,0.150427,677.547009
std,14981.649883,14981.649883,12.873998,10.922744,3.722975,2.290825,1.882228,0.163755,0.107114,0.229431,...,0.250704,0.0,0.419381,0.410247,0.306609,0.284189,3889.132647,0.485675,0.357796,28.276308
min,45.000000,46.000000,2.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.047000,...,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.444000,0.000000,0.000000,561.000000
25%,13186.000000,13187.000000,6.000000,2.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.379000,...,0.623000,1.0,0.000000,0.000000,0.000000,0.000000,7.101000,0.000000,0.000000,662.000000
50%,24711.000000,24712.000000,11.000000,5.000000,6.000000,1.000000,1.000000,0.105000,0.050000,0.538000,...,0.783000,1.0,0.333000,0.000000,0.133000,0.000000,11.362000,0.000000,0.000000,676.000000
75%,38895.000000,38896.000000,18.000000,10.000000,8.000000,3.000000,2.000000,0.222000,0.143000,0.692000,...,0.918000,1.0,0.909000,0.667000,0.400000,0.333000,18.981000,1.000000,0.000000,694.000000
max,51282.000000,51283.000000,129.000000,122.000000,24.000000,16.000000,11.000000,0.889000,0.600000,1.000000,...,1.044000,1.0,1.000000,1.000000,1.000000,1.000000,83672.100000,1.000000,1.000000,795.000000


In [7]:
df[['AGE','Credit_Score','Approved_Flag']].head()

,AGE,Credit_Score,Approved_Flag
0,25,651,P4
1,32,672,P2
2,34,689,P2
3,28,649,P4
4,25,662,P3


In [8]:
X = df.drop(columns=['Credit_Score'])
y = df['Credit_Score']

In [9]:
obj_cols = X.select_dtypes(include='object').columns

X = pd.get_dummies(X, columns=obj_cols, drop_first=True)

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [11]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies the convergence criterion of the underlying solver. `tol` isset as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. `tol` is set as `cond` of:func:`scipy.linalg.lstsq` when fitting on dense training data... versionadded:: 1.7.. versionchanged:: 1.9 Now supported on dense data, interpreted as the `cond` parameter.",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary <n_jobs>` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False
Name,Type,Value
"coef_ coef_: array of shape (n_features, ) or (n_targets, n_features)Estimated coefficients for the linear regression problem.If multiple targets are passed during the fit (y 2D), thisis a 2D array of shape (n_targets, n_features), while if onlyone target is passed, this is a 1D array of length n_features.","ndarray[float64](102,)","[ -0. , -0. , 0.1 ,..., -8.19,-11.71,-16.15]"
"feature_names_in_ feature_names_in_: ndarray of shape (`n_features_in_`,)Names of features seen during :term:`fit`. Defined only when `X`has feature names that are all strings... versionadded:: 1.0","ndarray[object](102,)","['Unnamed: 0','PROSPECTID','Total_TL',...,'Approved_Flag_P2', 'Approved_Flag_P3','Approved_Flag_P4']"
"intercept_ intercept_: float or array of shape (n_targets,)Independent term in the linear model. Set to 0.0 if`fit_intercept = False`.",float64,680.8
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,102
rank_ rank_: intRank of matrix `X`. Only available when `X` is dense.,int64,np.int64(85)


In [12]:
y_pred = model.predict(X_test)

In [14]:
r2 = (y_test, y_pred)

In [16]:
from sklearn.metrics import r2_score

print("R2 Score:", r2_score(y_test, y_pred))

R2 Score: 0.9485966348010563


In [17]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test, y_pred)

print("MAE:", mae)

MAE: 5.12897524674055


In [18]:
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test, y_pred)

print("MSE:", mse)

MSE: 35.60736529259563


In [19]:
rmse = np.sqrt(mse)

print("RMSE:", rmse)

RMSE: 5.967190737071812


In [ ]:
X = df.drop(columns=['Approved_Flag'])
y = df['Approved_Flag']

In [ ]:
obj_cols = X.select_dtypes(include='object').columns

X = pd.get_dummies(X, columns=obj_cols, drop_first=True)

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train, Y_train)

c:\Users\Sumit's\OneDrive\Desktop\M.L_01\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


,"max_iter max_iter: int, default=100Maximum number of iterations taken for the solvers to converge.",1000
,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary <random_state>` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is '

In [ ]:
Y_pred = model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(Y_test, Y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.6239316239316239


In [ ]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(Y_test, Y_pred)

print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[13  7  0  0]
 [ 4 42  1  6]
 [ 1 16  1  3]
 [ 0  3  3 17]]


In [ ]:
from sklearn.metrics import classification_report

print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

          P1       0.72      0.65      0.68        20
          P2       0.62      0.79      0.69        53
          P3       0.20      0.05      0.08        21
          P4       0.65      0.74      0.69        23

    accuracy                           0.62       117
   macro avg       0.55      0.56      0.54       117
weighted avg       0.57      0.62      0.58       117



In [ ]:
import math

def sigmoid(z):
    return 1 / (1 + math.exp(-z))

# Test
print(sigmoid(2))

0.8807970779778823


In [ ]:
def sigmoid(z):
    return 1 / (1 + math.exp(-z))

values = [-5, -4, -3, -2, -1, 0, 1, 2, 3, 4]

for i in values:
    print(f"Sigmoid({i}) = {sigmoid(i):.4f}")

Sigmoid(-5) = 0.0067
Sigmoid(-4) = 0.0180
Sigmoid(-3) = 0.0474
Sigmoid(-2) = 0.1192
Sigmoid(-1) = 0.2689
Sigmoid(0) = 0.5000
Sigmoid(1) = 0.7311
Sigmoid(2) = 0.8808
Sigmoid(3) = 0.9526
Sigmoid(4) = 0.9820
